language: node_js
node_js:
- '6'
env:
  global:
  - secure: sgATPZIrPFzghlmkDWRSNUCm6/Yv2dKwVaLc+QnKOV9DgqcvyLTK6EGKrKN/JTE5/nyXLA7g4M/TmQhb5yp6/9QbRf1BJhAqKfPHtoNX4TIB0BBzfILof8uQHJ8qEZt0gz2M4uEm0JA3Fz85tfaQwj+V+mlCGA8Ec4+aIpfWZa0mROJLNHEkouLEDBuxrQFLhZik11tyBngiK7LJUBfEe3xWF2tqNwxjf5TyqidEsoPQ/Vkf+hWXFM4JkBvROidw4erlVS66mX4uDKPz8QwqLq0G9ljVeealNwQmP0nJCNPbXPjwcMjHsozBW5LscFmrfDywOM4AYXwrhXtDvSpfmLNRUaXHx1q4wXLYTlCahUe0gx7Mv7FhGxqfgqOZBC0jjUr99g7V0F3J8ZUbicWGKj6AGFGTaX2k82oxGnCYhN4LdTCdT83zVegW/Ejmx/q8wdiDhQoq9VRY0wDPvWkx63sfIluF3s7FHjTFeJcXnHnV1tHiQxw+ezJwqdAMaR7lnnvkCtX02N7dc9gE6Pg4lupT6kqHt9L2Kf58mLu19Lm23LRxbiuDr6cNxy3CRjfugu25c5qtbk/VspzM4u4mkA8JBpxaSUD4KXr4BG8LAAowdOI7mUqQDv/An6ZcnFqWop0L11Zcp/QJXyNJYpP0UhlfIlGvZI+hfIUe4rbqQ8E=
